services:
  students:
    build: ./student_service
    ports:
      - "8001:8000"

  internships:
    build: ./internship_service
    ports:
      - "8002:8000"

  applications:
    build: ./application_service
    ports:
      - "8003:8000"
    depends_on:
      - students
      - internships
